//! Symbols that are not emoji, by category: what people look up a character
//! map for. Each entry is the character and the words it is found by.

pub const CATEGORIES: &[(&str, &str, &[(&str, &str)])] = &[
    (
        "arrows",
        "Arrows",
        &[
            ("←", "left arrow"),
            ("→", "right arrow"),
            ("↑", "up arrow"),
            ("↓", "down arrow"),
            ("↔", "left right arrow"),
            ("↕", "up down arrow"),
            ("↖", "north west arrow"),
            ("↗", "north east arrow"),
            ("↘", "south east arrow"),
            ("↙", "south west arrow"),
            ("⇐", "left double arrow"),
            ("⇒", "right double arrow implies"),
            ("⇑", "up double arrow"),
            ("⇓", "down double arrow"),
            ("⇔", "left right double arrow if and only if"),
            ("↩", "return left hook arrow"),
            ("↪", "right hook arrow"),
            ("↺", "anticlockwise open circle arrow undo"),
            ("↻", "clockwise open circle arrow redo"),
            ("⟵", "long left arrow"),
            ("⟶", "long right arrow"),
            ("⟷", "long left right arrow"),
            ("➜", "heavy round tipped right arrow"),
            ("➔", "heavy wide right arrow"),
            ("▲", "black up triangle"),
            ("▼", "black down triangle"),
            ("◀", "black left triangle"),
            ("▶", "black right triangle play"),
            ("△", "white up triangle"),
            ("▽", "white down triangle"),
            ("‹", "single left angle quotation"),
            ("›", "single right angle quotation"),
            ("«", "left double angle quotation guillemet"),
            ("»", "right double angle quotation guillemet"),
        ],
    ),
    (
        "keyboard",
        "Keyboard",
        &[
            ("⌘", "command key cmd"),
            ("⌥", "option key alt"),
            ("⇧", "shift key"),
            ("⌃", "control key ctrl"),
            ("⇪", "caps lock key"),
            ("⏎", "return key enter"),
            ("↵", "enter key return"),
            ("⌫", "delete backspace key"),
            ("⌦", "forward delete key"),
            ("⇥", "tab key"),
            ("⇤", "back tab key"),
            ("⎋", "escape key esc"),
            ("⏏", "eject key"),
            ("⌂", "home key house"),
            ("⇞", "page up key"),
            ("⇟", "page down key"),
            ("↖", "home key"),
            ("↘", "end key"),
            ("␣", "space key open box"),
            ("⊞", "windows key squared plus"),
        ],
    ),
    (
        "math",
        "Math",
        &[
            ("±", "plus minus"),
            ("∓", "minus plus"),
            ("×", "multiplication times"),
            ("÷", "division divide"),
            ("−", "minus sign"),
            ("≠", "not equal"),
            ("≈", "almost equal approximately"),
            ("≡", "identical to equivalent"),
            ("≤", "less than or equal"),
            ("≥", "greater than or equal"),
            ("≪", "much less than"),
            ("≫", "much greater than"),
            ("∞", "infinity"),
            ("√", "square root"),
            ("∛", "cube root"),
            ("∑", "sum sigma summation"),
            ("∏", "product pi"),
            ("∫", "integral"),
            ("∂", "partial derivative"),
            ("∆", "increment delta"),
            ("∇", "nabla del"),
            ("∝", "proportional to"),
            ("∠", "angle"),
            ("⊥", "perpendicular up tack"),
            ("∥", "parallel"),
            ("°", "degree"),
            ("′", "prime minute"),
            ("″", "double prime second"),
            ("‰", "per mille"),
            ("∈", "element of in"),
            ("∉", "not an element of"),
            ("∋", "contains as member"),
            ("⊂", "subset of"),
            ("⊃", "superset of"),
            ("⊆", "subset of or equal"),
            ("⊇", "superset of or equal"),
            ("∪", "union"),
            ("∩", "intersection"),
            ("∅", "empty set"),
            ("∀", "for all"),
            ("∃", "there exists"),
            ("∄", "there does not exist"),
            ("¬", "not sign negation"),
            ("∧", "logical and"),
            ("∨", "logical or"),
            ("⊕", "circled plus xor"),
            ("⊗", "circled times tensor"),
            ("∴", "therefore"),
            ("∵", "because"),
            ("ℕ", "natural numbers"),
            ("ℤ", "integers"),
            ("ℚ", "rational numbers"),
            ("ℝ", "real numbers"),
            ("ℂ", "complex numbers"),
            ("π", "pi"),
            ("ℯ", "euler e"),
            ("ƒ", "function florin"),
        ],
    ),
    (
        "fractions",
        "Fractions and Scripts",
        &[
            ("½", "one half fraction"),
            ("⅓", "one third fraction"),
            ("⅔", "two thirds fraction"),
            ("¼", "one quarter fraction"),
            ("¾", "three quarters fraction"),
            ("⅕", "one fifth fraction"),
            ("⅛", "one eighth fraction"),
            ("⁰", "superscript zero"),
            ("¹", "superscript one"),
            ("²", "superscript two squared"),
            ("³", "superscript three cubed"),
            ("⁴", "superscript four"),
            ("⁵", "superscript five"),
            ("⁶", "superscript six"),
            ("⁷", "superscript seven"),
            ("⁸", "superscript eight"),
            ("⁹", "superscript nine"),
            ("⁺", "superscript plus"),
            ("⁻", "superscript minus"),
            ("ⁿ", "superscript n"),
            ("₀", "subscript zero"),
            ("₁", "subscript one"),
            ("₂", "subscript two"),
            ("₃", "subscript three"),
            ("₄", "subscript four"),
            ("ₓ", "subscript x"),
        ],
    ),
    (
        "currency",
        "Currency",
        &[
            ("$", "dollar"),
            ("€", "euro"),
            ("£", "pound sterling"),
            ("¥", "yen yuan renminbi"),
            ("₩", "won korea"),
            ("₹", "rupee india"),
            ("₽", "ruble russia"),
            ("₺", "lira turkey"),
            ("₫", "dong vietnam"),
            ("₱", "peso philippines"),
            ("₪", "shekel israel"),
            ("₴", "hryvnia ukraine"),
            ("₦", "naira nigeria"),
            ("฿", "baht thailand"),
            ("₿", "bitcoin"),
            ("¢", "cent"),
            ("¤", "currency sign"),
        ],
    ),
    (
        "punctuation",
        "Punctuation and Typography",
        &[
            ("–", "en dash"),
            ("—", "em dash"),
            ("…", "ellipsis"),
            ("·", "middle dot interpunct"),
            ("•", "bullet"),
            ("‣", "triangular bullet"),
            ("‘", "left single quotation mark"),
            ("’", "right single quotation mark apostrophe"),
            ("“", "left double quotation mark"),
            ("”", "right double quotation mark"),
            ("„", "double low quotation mark"),
            ("「", "left corner bracket"),
            ("」", "right corner bracket"),
            ("『", "left white corner bracket"),
            ("』", "right white corner bracket"),
            ("【", "left black lenticular bracket"),
            ("】", "right black lenticular bracket"),
            ("〈", "left angle bracket"),
            ("〉", "right angle bracket"),
            ("《", "left double angle bracket"),
            ("》", "right double angle bracket"),
            ("¡", "inverted exclamation"),
            ("¿", "inverted question"),
            ("§", "section"),
            ("¶", "pilcrow paragraph"),
            ("†", "dagger"),
            ("‡", "double dagger"),
            ("©", "copyright"),
            ("®", "registered"),
            ("™", "trademark"),
            ("℠", "service mark"),
            ("№", "numero number"),
            ("℃", "degree celsius"),
            ("℉", "degree fahrenheit"),
            ("µ", "micro"),
            ("Ω", "ohm omega"),
            ("‰", "per mille"),
            ("※", "reference mark"),
            ("〃", "ditto mark"),
            ("々", "ideographic iteration mark"),
            ("〒", "postal mark"),
            ("\u{00A0}", "non breaking space nbsp"),
            ("\u{200B}", "zero width space"),
        ],
    ),
    (
        "greek",
        "Greek",
        &[
            ("α", "alpha"),
            ("β", "beta"),
            ("γ", "gamma"),
            ("δ", "delta"),
            ("ε", "epsilon"),
            ("ζ", "zeta"),
            ("η", "eta"),
            ("θ", "theta"),
            ("ι", "iota"),
            ("κ", "kappa"),
            ("λ", "lambda"),
            ("μ", "mu"),
            ("ν", "nu"),
            ("ξ", "xi"),
            ("ο", "omicron"),
            ("ρ", "rho"),
            ("σ", "sigma"),
            ("τ", "tau"),
            ("υ", "upsilon"),
            ("φ", "phi"),
            ("χ", "chi"),
            ("ψ", "psi"),
            ("ω", "omega"),
            ("Γ", "capital gamma"),
            ("Δ", "capital delta"),
            ("Θ", "capital theta"),
            ("Λ", "capital lambda"),
            ("Ξ", "capital xi"),
            ("Π", "capital pi"),
            ("Σ", "capital sigma"),
            ("Φ", "capital phi"),
            ("Ψ", "capital psi"),
            ("Ω", "capital omega"),
        ],
    ),
    (
        "shapes",
        "Shapes and Marks",
        &[
            ("✓", "check mark tick"),
            ("✔", "heavy check mark"),
            ("✗", "ballot x cross"),
            ("✘", "heavy ballot x"),
            ("☐", "ballot box unchecked"),
            ("☑", "ballot box with check"),
            ("☒", "ballot box with x"),
            ("★", "black star"),
            ("☆", "white star"),
            ("♥", "black heart suit"),
            ("♡", "white heart suit"),
            ("♦", "diamond suit"),
            ("♣", "club suit"),
            ("♠", "spade suit"),
            ("●", "black circle"),
            ("○", "white circle"),
            ("◉", "fisheye"),
            ("◎", "bullseye"),
            ("■", "black square"),
            ("□", "white square"),
            ("▪", "small black square"),
            ("▫", "small white square"),
            ("◆", "black diamond"),
            ("◇", "white diamond"),
            ("♪", "eighth note music"),
            ("♫", "beamed eighth notes music"),
            ("☀", "sun"),
            ("☁", "cloud"),
            ("☂", "umbrella"),
            ("☎", "telephone"),
            ("✉", "envelope"),
            ("✂", "scissors"),
            ("✎", "pencil"),
            ("⚠", "warning sign"),
            ("⚡", "high voltage"),
            ("☯", "yin yang"),
            ("☮", "peace"),
            ("♻", "recycling"),
            ("⌀", "diameter"),
            ("⌘", "place of interest"),
        ],
    ),
    (
        "box",
        "Box Drawing",
        &[
            ("─", "box horizontal light"),
            ("│", "box vertical light"),
            ("┌", "box down and right"),
            ("┐", "box down and left"),
            ("└", "box up and right"),
            ("┘", "box up and left"),
            ("├", "box vertical and right"),
            ("┤", "box vertical and left"),
            ("┬", "box down and horizontal"),
            ("┴", "box up and horizontal"),
            ("┼", "box vertical and horizontal"),
            ("═", "box double horizontal"),
            ("║", "box double vertical"),
            ("╔", "box double down and right"),
            ("╗", "box double down and left"),
            ("╚", "box double up and right"),
            ("╝", "box double up and left"),
            ("░", "light shade"),
            ("▒", "medium shade"),
            ("▓", "dark shade"),
            ("█", "full block"),
        ],
    ),
];
