//! How an extension's script becomes a [`PageModel`].
//!
//! The extension SDK has three modules:
//!
//! - `launcher`: the page nodes, registered as GPUI Shell components whose
//!   materializers draw nothing and carry a model value instead;
//! - `launcher/api`: host functions returning plain data, such as `launch()`,
//!   one module instance per extension (see [`HostApi::module_for`]);
//! - `launcher/utils`: plain JavaScript helpers for class-based views, such as
//!   `Query`, served from source (see [`utils_module_source`]).
//!
//! The launcher renders a command's `ScriptView` itself and takes the
//! [`PageModel`] out of the element it returns (see
//! [`crate::pages::ScriptPage`]), so a page is produced synchronously and its
//! callbacks always belong to the current render.

mod cache;
mod carrier;
mod components;
mod host_api;
#[cfg(test)]
mod tests;
mod utils;

use std::{
    cell::RefCell,
    path::{Path, PathBuf},
};

use anyhow::{Context as _, Result, anyhow};
use gpui_kit::{AnyElement, SharedString};
use gpui_shell::{ComponentRegistry, FrozenComponentRegistry};

pub use host_api::{
    CommandMetadata, EffectSink, ExtensionContext, HostApi, LaunchType, MetadataSink,
};
pub use utils::{UTILS_MODULE, utils_declarations, utils_module_source};

use crate::model::PageModel;

/// The module name extensions import page nodes from.
pub const COMPONENT_MODULE: &str = "launcher";

/// The launcher's component catalog. It holds only page nodes: an extension
/// cannot draw, so no styled component is registered.
pub fn components() -> Result<FrozenComponentRegistry> {
    let mut registry =
        ComponentRegistry::new(gpui_shell::COMPONENT_REGISTRY_API_VERSION, COMPONENT_MODULE)
            .map_err(|error| anyhow!("{error}"))?;
    components::register(&mut registry).map_err(|error| anyhow!("{error}"))?;
    registry.freeze().map_err(|error| anyhow!("{error}"))
}

/// Takes the page out of the element a command's `render` produced, or
/// explains what was returned instead.
///
/// When a node could not be built, the answer is why, not merely that no page
/// came back: the node's own sentence ("Action `Open` has no effect…") is the
/// one an author can act on.
pub fn take_page_model(element: &mut AnyElement) -> Result<PageModel, String> {
    let failure = carrier::take_failure();
    carrier::take::<PageModel>(element).ok_or_else(|| {
        failure.unwrap_or_else(|| {
            "a command's `render` must return a `List`, `Detail` or `Form` from the \
             `launcher` module"
                .into()
        })
    })
}

/// Writes what an extension author's editor needs to check an extension:
/// GPUI Shell's `gpui-kit.d.ts` and `jsconfig.json` with the `launcher`
/// components, `launcher.d.ts` naming them by their module, `launcher-api.d.ts` and `launcher-utils.d.ts` for the two
/// modules the component registry does not describe, and
/// `launcher.schema.json` for `launcher.json`. Answers the files it wrote; a
/// file already up to date is not rewritten, so an editor watching them is
/// not disturbed for nothing.
pub fn write_declarations(directory: &Path) -> Result<Vec<PathBuf>> {
    let mut written =
        gpui_shell::write_type_declarations_with_components(directory, &components()?)
            .with_context(|| format!("cannot write declarations to {}", directory.display()))?;
    let schema = serde_json::to_string_pretty(&super::manifest::schema())? + "\n";
    for (file, contents) in [
        // GPUI Shell declares a component registry under `gpui-component`
        // whatever its specifier, so the launcher's name is added beside it.
        (
            "launcher.d.ts",
            format!(
                "// Generated by the launcher; do not edit.\ndeclare module \"{COMPONENT_MODULE}\" {{\n  export * from \"gpui-component\";\n}}\n"
            ),
        ),
        (
            "launcher-api.d.ts",
            module_declaration(host_api::MODULE, host_api::DECLARATIONS),
        ),
        (
            "launcher-utils.d.ts",
            module_declaration(UTILS_MODULE, utils_declarations()),
        ),
        ("launcher.schema.json", schema),
    ] {
        let path = directory.join(file);
        if std::fs::read_to_string(&path).is_ok_and(|current| current == contents) {
            continue;
        }
        std::fs::write(&path, contents)
            .with_context(|| format!("cannot write {}", path.display()))?;
        written.push(path);
    }
    Ok(written)
}

fn module_declaration(module: &str, body: &str) -> String {
    format!(
        "// Generated by the launcher; do not edit.\n\
         declare module \"{module}\" {{\n  import type {{ Context, View }} from \"gpui-kit\";\n{body}}}\n"
    )
}

thread_local! {
    /// The extension whose page is being rendered, when the host says so.
    static RENDERING: RefCell<Option<SharedString>> = const { RefCell::new(None) };
    /// The extension launched last: the answer when nobody said otherwise,
    /// which is right for the page on top of the stack.
    static LAUNCHED: RefCell<Option<SharedString>> = const { RefCell::new(None) };
}

/// Runs `render` knowing which extension it renders for.
///
/// A materializer cannot ask which script produced its node, yet
/// `Action.launch("other-command")` must name a command of the same
/// extension. The host wraps a page's render in this so that answer is exact
/// for every page on the stack, not only the one launched last.
pub fn render_for_extension<R>(extension: &SharedString, render: impl FnOnce() -> R) -> R {
    let previous = RENDERING.with(|rendering| rendering.replace(Some(extension.clone())));
    let result = render();
    RENDERING.with(|rendering| rendering.replace(previous));
    result
}

pub(super) fn note_launched(extension: &SharedString) {
    LAUNCHED.with(|launched| launched.replace(Some(extension.clone())));
}

pub(super) fn current_extension() -> Option<SharedString> {
    RENDERING
        .with(|rendering| rendering.borrow().clone())
        .or_else(|| LAUNCHED.with(|launched| launched.borrow().clone()))
}
