[package]
name = "datakit-driver-sqlite"
description = "DataKit's SQLite driver."
version = "0.6.5"
publish = false
edition.workspace = true

[dependencies]
anyhow.workspace = true
datakit-catalog = { path = "../catalog" }
datakit-driver = { path = "../driver" }
futures = "0.3"
rusqlite = { version = "0.40", features = ["bundled", "column_decltype"] }
tracing.workspace = true

[dev-dependencies]
datakit-runtime = { path = "../runtime" }
tempfile = "3"
tokio = { version = "1", features = ["rt", "time"] }

[lints]
workspace = true
