use datakit_catalog::Column;
use datakit_driver::{Dialect, PlanNode, Value, ddl};

use crate::plan;

/// PostgreSQL's syntax.
pub struct PostgresDialect;

impl Dialect for PostgresDialect {
    fn reserved_words(&self) -> &'static [&'static str] {
        RESERVED
    }

    fn keywords(&self) -> &'static [&'static str] {
        KEYWORDS
    }

    fn functions(&self) -> &'static [&'static str] {
        FUNCTIONS
    }

    fn data_types(&self) -> &'static [&'static str] {
        DATA_TYPES
    }

    fn explain(&self, sql: &str, analyze: bool) -> Option<String> {
        let options = if analyze {
            "FORMAT JSON, ANALYZE, BUFFERS"
        } else {
            "FORMAT JSON"
        };
        Some(format!("EXPLAIN ({options}) {sql}"))
    }

    fn parse_plan(&self, rows: &[Vec<Value>]) -> anyhow::Result<PlanNode> {
        let text: Vec<String> = rows
            .iter()
            .filter_map(|row| row.first().and_then(Value::display))
            .map(|text| text.into_owned())
            .collect();
        plan::parse(&text.join("\n"))
    }

    fn column_definition(&self, column: &Column) -> String {
        // An identity column has no default expression; say how it is
        // assigned instead.
        if column.is_auto_increment() && column.default().is_none() {
            let mut definition = format!(
                "{} {} GENERATED BY DEFAULT AS IDENTITY",
                self.quote_identifier(&column.name()),
                column.data_type()
            );
            if !column.is_nullable() {
                definition.push_str(" NOT NULL");
            }
            return definition;
        }
        ddl::column_definition(self, column)
    }
}

/// Types offered when a column is created or changed, most common first.
const DATA_TYPES: &[&str] = &[
    "integer",
    "bigint",
    "smallint",
    "serial",
    "bigserial",
    "numeric",
    "numeric(12,2)",
    "real",
    "double precision",
    "boolean",
    "text",
    "varchar(255)",
    "char(1)",
    "uuid",
    "date",
    "time",
    "timestamp",
    "timestamptz",
    "interval",
    "json",
    "jsonb",
    "bytea",
    "inet",
    "cidr",
    "text[]",
    "integer[]",
];

/// Words PostgreSQL reserves outright or reserves except as function names;
/// an identifier spelled like either must be quoted. From the "Key Words"
/// appendix of the PostgreSQL manual.
const RESERVED: &[&str] = &[
    "ALL",
    "ANALYSE",
    "ANALYZE",
    "AND",
    "ANY",
    "ARRAY",
    "AS",
    "ASC",
    "ASYMMETRIC",
    "AUTHORIZATION",
    "BINARY",
    "BOTH",
    "CASE",
    "CAST",
    "CHECK",
    "COLLATE",
    "COLLATION",
    "COLUMN",
    "CONCURRENTLY",
    "CONSTRAINT",
    "CREATE",
    "CROSS",
    "CURRENT_CATALOG",
    "CURRENT_DATE",
    "CURRENT_ROLE",
    "CURRENT_SCHEMA",
    "CURRENT_TIME",
    "CURRENT_TIMESTAMP",
    "CURRENT_USER",
    "DEFAULT",
    "DEFERRABLE",
    "DESC",
    "DISTINCT",
    "DO",
    "ELSE",
    "END",
    "EXCEPT",
    "FALSE",
    "FETCH",
    "FOR",
    "FOREIGN",
    "FREEZE",
    "FROM",
    "FULL",
    "GRANT",
    "GROUP",
    "HAVING",
    "ILIKE",
    "IN",
    "INITIALLY",
    "INNER",
    "INTERSECT",
    "INTO",
    "IS",
    "ISNULL",
    "JOIN",
    "LATERAL",
    "LEADING",
    "LEFT",
    "LIKE",
    "LIMIT",
    "LOCALTIME",
    "LOCALTIMESTAMP",
    "NATURAL",
    "NOT",
    "NOTNULL",
    "NULL",
    "OFFSET",
    "ON",
    "ONLY",
    "OR",
    "ORDER",
    "OUTER",
    "OVERLAPS",
    "PLACING",
    "PRIMARY",
    "REFERENCES",
    "RETURNING",
    "RIGHT",
    "SELECT",
    "SESSION_USER",
    "SIMILAR",
    "SOME",
    "SYMMETRIC",
    "SYSTEM_USER",
    "TABLE",
    "TABLESAMPLE",
    "THEN",
    "TO",
    "TRAILING",
    "TRUE",
    "UNION",
    "UNIQUE",
    "USER",
    "USING",
    "VARIADIC",
    "VERBOSE",
    "WHEN",
    "WHERE",
    "WINDOW",
    "WITH",
];

/// Keywords offered by completion, most used first within each group.
const KEYWORDS: &[&str] = &[
    "SELECT",
    "FROM",
    "WHERE",
    "AND",
    "OR",
    "NOT",
    "JOIN",
    "LEFT JOIN",
    "INNER JOIN",
    "RIGHT JOIN",
    "FULL JOIN",
    "CROSS JOIN",
    "ON",
    "USING",
    "GROUP BY",
    "ORDER BY",
    "HAVING",
    "LIMIT",
    "OFFSET",
    "AS",
    "DISTINCT",
    "IN",
    "IS NULL",
    "IS NOT NULL",
    "LIKE",
    "ILIKE",
    "BETWEEN",
    "EXISTS",
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "END",
    "UNION",
    "UNION ALL",
    "INTERSECT",
    "EXCEPT",
    "WITH",
    "RECURSIVE",
    "INSERT INTO",
    "VALUES",
    "UPDATE",
    "SET",
    "DELETE FROM",
    "RETURNING",
    "ON CONFLICT",
    "DO NOTHING",
    "DO UPDATE",
    "MERGE INTO",
    "CREATE TABLE",
    "CREATE VIEW",
    "CREATE MATERIALIZED VIEW",
    "CREATE INDEX",
    "CREATE SCHEMA",
    "CREATE FUNCTION",
    "CREATE OR REPLACE",
    "ALTER TABLE",
    "ADD COLUMN",
    "DROP COLUMN",
    "DROP TABLE",
    "DROP VIEW",
    "DROP INDEX",
    "TRUNCATE",
    "PRIMARY KEY",
    "FOREIGN KEY",
    "REFERENCES",
    "UNIQUE",
    "CHECK",
    "DEFAULT",
    "NOT NULL",
    "BEGIN",
    "COMMIT",
    "ROLLBACK",
    "SAVEPOINT",
    "EXPLAIN",
    "EXPLAIN ANALYZE",
    "ANALYZE",
    "VACUUM",
    "GRANT",
    "REVOKE",
    "NULL",
    "TRUE",
    "FALSE",
    "ASC",
    "DESC",
    "NULLS FIRST",
    "NULLS LAST",
    "OVER",
    "PARTITION BY",
    "WINDOW",
    "LATERAL",
    "FILTER",
    "COLLATE",
    "INTERVAL",
];

/// Built-in functions offered by completion.
const FUNCTIONS: &[&str] = &[
    "count",
    "sum",
    "avg",
    "min",
    "max",
    "coalesce",
    "nullif",
    "greatest",
    "least",
    "now",
    "current_date",
    "date_trunc",
    "date_part",
    "extract",
    "age",
    "to_char",
    "to_date",
    "to_timestamp",
    "length",
    "lower",
    "upper",
    "trim",
    "substring",
    "replace",
    "split_part",
    "concat",
    "concat_ws",
    "string_agg",
    "array_agg",
    "unnest",
    "array_length",
    "jsonb_build_object",
    "jsonb_agg",
    "json_agg",
    "jsonb_array_elements",
    "jsonb_extract_path_text",
    "to_jsonb",
    "row_number",
    "rank",
    "dense_rank",
    "lag",
    "lead",
    "first_value",
    "last_value",
    "generate_series",
    "gen_random_uuid",
    "round",
    "abs",
    "ceil",
    "floor",
    "random",
    "regexp_replace",
    "regexp_matches",
    "pg_size_pretty",
    "pg_total_relation_size",
];
