[package]
name = "datakit-sql"
description = "DataKit's understanding of SQL text: lexing, statement boundaries and completion."
version = "0.6.5"
publish = false
edition.workspace = true

[dependencies]
datakit-catalog = { path = "../catalog" }
datakit-driver = { path = "../driver" }
sqlformat = "0.3"

[lints]
workspace = true
