[package]
name = "datakit-driver-redis"
description = "DataKit's Redis driver."
version = "0.6.5"
publish = false
edition.workspace = true

[dependencies]
anyhow.workspace = true
datakit-catalog = { path = "../catalog" }
datakit-driver = { path = "../driver" }
futures = "0.3"
redis = { version = "1", features = ["tokio-comp"] }
tokio = { version = "1", features = ["sync"] }

[dev-dependencies]
datakit-runtime = { path = "../runtime" }

[lints]
workspace = true
